### PR TITLE
update primary color to fix #24

### LINKED ISSUE #24: White wallpaper in media-control card
Since 0.23, the wallpaper of media control cards is white:
image

Installed version: .024
image

Tested on Firefox and Edge chromium

### PR DESCRIPTION
**Pull request by CyanoFresh**
This change was suggested in https://github.com/bbbenji/synthwave-hass/issues/24#issuecomment-616229998

### CODE REVIEW

**Comment by bbbenji** [comment]
Works well, thanks!

**Comment by bbbenji** [comment]
This fix has the side effect of breaking the active toolbar tabs on the Supervisor page.

Screen Shot 2020-05-02 at 4 07 18 PM

Instead of relying on `primary-color`, please define the color of the media card background separately. Once this is fixed, I will release a new version of this theme.

**Comment by CyanoFresh** [comment]
> This fix has the side effect of breaking the active toolbar tabs on the Supervisor page.
> 
> Screen Shot 2020-05-02 at 4 07 18 PM
> 
> Instead of relying on `primary-color`, please define the color of the media card background separately. Once this is fixed, I will release a new version of this theme.

yep, just found this bug, too.
Cannot find separate variable for media control card https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-media-control-card.ts . So to fix this we need to create PR on frontend repo? Or there is another way?

**Comment by bbbenji** [comment]
If you want to look into a workaround, it should be possible to fix via: https://github.com/bbbenji/synthwave-hass-extras

Of course, resolving this upstream would be ideal.

Since the media card is a higher priority, in my opinion, and the active toolbar tab is still somewhat visible, I will go ahead and release this change. Thanks!

**Pull request merged**
